- id: check-go-copyright
  name: Check copyright in go files
  entry: copyright-check.sh go
  files: '\.go$'
  language: 'script'
  description: This hook checks the copyright and fails if the copyright does not exist or is not up to date.
- id: check-scala-copyright
  name: Check copyright in Scala files
  entry: copyright-check.sh scala
  files: '\.scala$'
  language: 'script'
  description: This hook checks the copyright and fails if the copyright does not exist or is not up to date.
- id: check-python-copyright
  name: Check copyright in Python files
  entry: copyright-check.sh python
  files: '\.py$'
  language: 'script'
  description: This hook checks the copyright and fails if the copyright does not exist or is not up to date.
- id: go-fmt
  name: go fmt
  entry: go-format.sh
  files: '\.go$'
  language: 'script'
  description: Runs `gofmt`, requires golang.
- id: go-vet
  name: go vet
  entry: go-vet.sh
  files: '\.go$'
  language: 'script'
  description: Runs `go vet`, requires golang.
- id: go-lint
  name: golint
  entry: go-lint.sh
  files: '\.go$'
  language: 'script'
  description: Runs `go lint`, requires golang.
- id: golines
  name: golines
  entry: golines.sh
  files: '\.go$'
  language: 'script'
  description: Runs `golines`, requires golang and will install golines.
